[project]
dependencies = [
  "backoff>=2.2.1",
  "requests>=2.32.4",
]
description = "A Python package for mirroring USOM data for AdGuard formatted lists."
name = "usom-mirror"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
